language: ruby
env:
  global:
    - TRAVIS=true
rvm:
  - 2.1.1
services:
  - redis-server
before_script:
  - cp config/config.yml.example config/config.yml
  - psql -c "CREATE USER suploy WITH PASSWORD 'password1' CREATEDB;" -U postgres
  - bundle exec rake db:setup
bundler_args: ""
script: rspec spec
