language: ruby
env:
  global:
    - TRAVIS=true
  matrix:
    - TASK=rake
    - TASK=cucumber
rvm:
  - 2.1.1
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libicu-dev
before_script:
  - cp config/config.yml.travis config/config.yml
  - psql -c "CREATE USER suploy WITH PASSWORD 'password1' CREATEDB;" -U postgres
  - bundle exec rake db:setup
bundler_args: ""
script:
  - bundle exec $TASK
notifications:
  webhooks:
    - http://hubot-james.herokuapp.com/hubot/travis?room=%23kreisverkehr&type=groupchat
