development:
  adapter: postgresql
  template: template0
  encoding: utf8
  collation: en_US.UTF8
  ctype: en_US.UTF8
  database: suploy_development
  host: localhost
  pool: 5
  username: suploy
  password: password1

test:
  adapter: postgresql
  template: template0
  encoding: utf8
  collation: en_US.UTF8
  ctype: en_US.UTF8
  database: suploy_test
  host: localhost
  pool: 5
  username: suploy
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: suploy_production
  host: localhost
  pool: 5
  username: suploy
  password: password1
