#!/bin/bash
port=5000
name=`pwd | awk -F/ '{print $NF}' | sed 's/....$//'`
image_name="$name"image
git archive --format=tar master | ~/buildstep/buildstep $image_name
container=$(docker run -p $port -d --name $name $image_name /bin/bash -c "/start web")
public_port=$(docker port $container $port)

echo "Find your app at: $(hostname):$public_port"

# create subdomain with nginx

