#!/bin/bash
port=5000
name=$(date +%s)
git archive --format=tar master | ~/buildstep/buildstep $name
container=$(docker run -p $port -d $name /bin/bash -c "/start web")
public_port=$(docker port $container $port)

echo "Find your app at: $(hostname):$public_port"

# create subdomain with nginx

